(()=>{"use strict";
const D=window.NUSAMONITOR_DATA;if(!D||!window.L)return;
const colors={critical:"#ff5667",high:"#ff9d4d",medium:"#f4d35e",low:"#2bd47d"},weights={critical:100,high:75,medium:45,low:20};
const names=Object.fromEntries(D.layers.map(x=>[x.id,x.label]));
const S={layer:"all",search:"",hours:24,feed:"all",visible:[],markers:new Map()};
const $=s=>document.querySelector(s);
const E={layers:$("#layer-list"),title:$("#map-title"),eventCount:$("#visible-event-count"),countryCount:$("#country-count"),risk:$("#risk-score"),riskFill:$("#risk-fill"),critical:$("#critical-count"),high:$("#high-count"),medium:$("#medium-count"),low:$("#low-count"),search:$("#global-search"),feedFilter:$("#feed-filter"),feed:$("#feed-list"),brief:$("#ai-brief"),confidence:$("#confidence-value"),range:$("#timeline-range"),rangeLabel:$("#timeline-label"),panel:$("#selected-event-panel"),panelCat:$("#selected-category"),panelTitle:$("#selected-title"),panelSummary:$("#selected-summary"),panelMeta:$("#selected-meta"),clock:$("#utc-clock"),sidebar:$("#sidebar"),palette:$("#command-palette"),commandInput:$("#command-input"),commandList:$("#command-list")};
const map=L.map("map",{center:[12,18],zoom:2.35,minZoom:2,maxZoom:9,worldCopyJump:true});
L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{attribution:"&copy; OpenStreetMap &copy; CARTO",subdomains:"abcd",maxZoom:19}).addTo(map);
const group=L.layerGroup().addTo(map);
const commands=[
["Focus Indonesia","Map",()=>map.flyTo([-2.5,118],4.25,{duration:1.2})],
["Show Global View","Map",()=>map.flyTo([12,18],2.35,{duration:1.2})],
["Filter Conflict Layer","Layer",()=>setLayer("conflict")],
["Filter Disaster Layer","Layer",()=>setLayer("disaster")],
["Filter Indonesia Signals","Search",()=>setSearch("Indonesia")],
["Reset Dashboard","System",reset]
];
function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function renderLayers(){E.layers.innerHTML=D.layers.map(l=>`<button class="layer-button ${l.id===S.layer?"active":""}" data-layer="${l.id}"><span class="layer-icon">${l.icon}</span><span>${l.label}</span><span class="layer-count">${l.id==="all"?D.events.length:D.events.filter(e=>e.category===l.id).length}</span></button>`).join("")}
function setLayer(id){S.layer=id;renderLayers();apply()}
function setSearch(v){S.search=v.trim().toLowerCase();E.search.value=v;apply()}
function reset(){S.layer="all";S.search="";S.hours=24;S.feed="all";E.search.value="";E.range.value="24";E.feedFilter.value="all";renderLayers();apply();map.flyTo([12,18],2.35,{duration:1})}
function apply(){S.visible=D.events.filter(e=>{const t=[e.title,e.category,e.country,e.region,e.summary,...e.tags].join(" ").toLowerCase();return(S.layer==="all"||e.category===S.layer)&&e.ageHours<=S.hours&&(!S.search||t.includes(S.search))});E.title.textContent=names[S.layer]||"Intelligence Layer";renderMarkers();metrics();feed();brief()}
function renderMarkers(){group.clearLayers();S.markers.clear();S.visible.forEach(e=>{const c=colors[e.severity],m=L.marker([e.lat,e.lng],{icon:L.divIcon({className:"custom-marker",html:`<span class="custom-marker-pulse" style="--marker:${c}"></span><span class="custom-marker-core" style="--marker:${c}"></span>`,iconSize:[28,28],iconAnchor:[14,14]})});m.bindPopup(`<div class="intel-popup"><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p><div class="popup-meta"><span>${esc(e.region)}</span><span>${e.ageHours}h ago</span><span>${e.severity.toUpperCase()}</span></div></div>`);m.on("click",()=>select(e));m.addTo(group);S.markers.set(e.id,m)})}
function metrics(){const c={critical:0,high:0,medium:0,low:0},countries=new Set();let total=0;S.visible.forEach(e=>{c[e.severity]++;countries.add(e.country);total+=weights[e.severity]});const risk=Math.max(8,Math.min(96,Math.round(total/Math.max(S.visible.length,1))));E.eventCount.textContent=S.visible.length;E.countryCount.textContent=countries.size;E.critical.textContent=c.critical;E.high.textContent=c.high;E.medium.textContent=c.medium;E.low.textContent=c.low;E.risk.textContent=risk;E.riskFill.style.width=risk+"%"}
function feed(){const ids=new Set(S.visible.map(e=>e.id));const items=D.news.filter(n=>{const e=D.events.find(x=>x.id===n.eventId);return ids.has(n.eventId)&&(S.feed==="all"||n.severity===S.feed||(S.feed==="indonesia"&&e?.country==="Indonesia"))});E.feed.innerHTML=(items.length?items:[{eventId:"",severity:"low",region:"System",age:"Now",title:"Tidak ada signal yang sesuai filter aktif.",summary:"Ubah layer, rentang waktu, atau pencarian."}]).map(n=>`<article class="feed-card" data-event-id="${n.eventId}" style="--feed:${colors[n.severity]}"><span class="feed-severity"></span><div><div class="feed-card-head"><span>${esc(n.region)} · ${n.severity}</span><span>${esc(n.age)}</span></div><h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p></div></article>`).join("")}
function brief(){const e=S.visible,critical=e.filter(x=>x.severity==="critical"),high=e.filter(x=>x.severity==="high"),indo=e.filter(x=>x.country==="Indonesia"),top=e[0]?.region||"global monitoring area";E.brief.innerHTML=`<strong>${e.length} active signals</strong> match the current dashboard filters. ${critical.length?`<strong>${critical.length} critical event${critical.length>1?"s":""}</strong> require immediate attention, led by ${esc(top)}.`:"No critical signals are visible."} ${high.length?`${high.length} high-severity indicator${high.length>1?"s":""} may affect logistics, infrastructure, or regional stability.`:"High-severity pressure remains limited."} ${indo.length?`${indo.length} Indonesia-related signal${indo.length>1?"s are":" is"} active.`:"No Indonesia-specific signal matches the filters."}`;E.confidence.textContent=Math.max(58,Math.min(94,66+e.length*2+critical.length*4))+"%"}
function select(e){E.panelCat.textContent=`${e.category.toUpperCase()} · ${e.severity.toUpperCase()}`;E.panelTitle.textContent=e.title;E.panelSummary.textContent=e.summary;E.panelMeta.innerHTML=[e.region,e.country,`${e.ageHours}h ago`,e.source].map(v=>`<span>${esc(v)}</span>`).join("");E.panel.classList.add("visible")}
function focus(id){const e=D.events.find(x=>x.id===id);if(!e)return;if(!S.visible.some(x=>x.id===id)){S.layer="all";S.search="";S.hours=Math.max(24,e.ageHours);E.search.value="";E.range.value=S.hours;renderLayers();apply()}map.flyTo([e.lat,e.lng],Math.max(map.getZoom(),5),{duration:1});setTimeout(()=>{S.markers.get(id)?.openPopup();select(e)},800)}
function clock(){E.clock.textContent=new Intl.DateTimeFormat("en-GB",{timeZone:"UTC",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date())}
function renderCommands(items=commands){E.commandList.innerHTML=items.map(c=>`<button class="command-item" data-i="${commands.indexOf(c)}"><span>${c[0]}</span><span>${c[1]}</span></button>`).join("")}
function openPalette(){E.palette.hidden=false;E.commandInput.value="";renderCommands();setTimeout(()=>E.commandInput.focus(),20)}function closePalette(){E.palette.hidden=true}
E.layers.addEventListener("click",e=>{const b=e.target.closest("[data-layer]");if(b)setLayer(b.dataset.layer)});E.search.addEventListener("input",e=>setSearch(e.target.value));E.range.addEventListener("input",e=>{S.hours=+e.target.value;E.rangeLabel.textContent=`Last ${S.hours} hours`;apply()});E.feedFilter.addEventListener("change",e=>{S.feed=e.target.value;feed()});E.feed.addEventListener("click",e=>{const c=e.target.closest("[data-event-id]");if(c?.dataset.eventId)focus(c.dataset.eventId)});
$("#focus-indonesia").onclick=()=>map.flyTo([-2.5,118],4.25,{duration:1.2});$("#focus-world").onclick=()=>map.flyTo([12,18],2.35,{duration:1.2});$("#toggle-pulse").onclick=e=>{document.body.classList.toggle("no-pulse");e.currentTarget.setAttribute("aria-pressed",String(!document.body.classList.contains("no-pulse")))};$("#refresh-button").onclick=()=>apply();$("#close-event-panel").onclick=()=>E.panel.classList.remove("visible");$("#mobile-menu-button").onclick=()=>E.sidebar.classList.toggle("open");$("#command-backdrop").onclick=closePalette;E.commandInput.addEventListener("input",e=>renderCommands(commands.filter(c=>c[0].toLowerCase().includes(e.target.value.toLowerCase()))));E.commandList.addEventListener("click",e=>{const b=e.target.closest("[data-i]");if(b){commands[+b.dataset.i][2]();closePalette()}});
document.addEventListener("keydown",e=>{const tag=document.activeElement?.tagName,typing=["INPUT","TEXTAREA","SELECT"].includes(tag);if(e.key==="/"&&!typing){e.preventDefault();E.search.focus()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openPalette()}if(e.key==="Escape"){E.panel.classList.remove("visible");if(!E.palette.hidden)closePalette()}});
renderLayers();apply();clock();setInterval(clock,1000);renderCommands();if("serviceWorker"in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("./sw.js").catch(()=>{});
})();